---
apiVersion: v1
kind: Service
metadata:
  name: my-argocd-test-app-service
  namespace: leti
spec:
  type: ClusterIp
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
  selector:
    app: test-app 
