---
apiVersion: v1
kind: Service
metadata:
  name: second_service-name
  namespace: leti
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  selector:
    app: test-app 