---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-argocd-test-app-deployment
  namespace: leti
spec:
  template: 
    metadata:
      name : my-argocd-test-app
      labels:
        app: test-app
    spec: 
      containers:
      - name: test
        image: nginx
  replicas: 2
  selector:
    matchLabels:
      app: test-app
...
